# Generated by Django 2.1.5 on 2021-03-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='abhudhaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankname', models.CharField(max_length=1000)),
                ('IFSC', models.CharField(max_length=1000)),
                ('office', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
