# Generated by Django 2.1.5 on 2021-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210316_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ahmedabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BANKNAME', models.CharField(max_length=1000)),
                ('IFSC', models.CharField(max_length=1000)),
                ('OFFICE', models.CharField(max_length=1000)),
                ('ADDRESS', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='abhudhaya',
            old_name='address',
            new_name='ADDRESS',
        ),
        migrations.RenameField(
            model_name='abhudhaya',
            old_name='Bankname',
            new_name='BANKNAME',
        ),
        migrations.RenameField(
            model_name='abhudhaya',
            old_name='office',
            new_name='OFFICE',
        ),
    ]
