# Generated by Django 2.1.5 on 2021-03-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20210316_1519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='abhudhaya',
            new_name='abhyudaya',
        ),
    ]
