# Generated by Django 2.1.5 on 2021-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20210316_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abhyudaya',
            name='ADDRESS',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='abhyudaya',
            name='BANKNAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='abhyudaya',
            name='IFSC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='abhyudaya',
            name='OFFICE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ahmedabad',
            name='ADDRESS',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ahmedabad',
            name='BANKNAME',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ahmedabad',
            name='IFSC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ahmedabad',
            name='OFFICE',
            field=models.CharField(max_length=100),
        ),
    ]
